version: "3"
services:
  nginx:
    image: nginx 
    container_name: nginx2
    ports: 
      - "5000:80"
    volumes:
      - ./www/:/var/www/html/:rw
      - ./conf/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/nginx/:/var/log/nginx/:rw
    links:
      - php-fpm54:php

  php-fpm54:
    image: twenj/lnmp-php54:v2
    container_name: myphp-fpm54
    volumes:
      - ./www/:/var/www/html/:rw
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./log/php-fpm/:/var/log/php-fpm/:rw
    links:
      - mysql:mysql
      - redis:redis
    environment:
      APP_ENV: "local"

  mysql:
    image: mysql:5.7
    container_name: mysql57
    ports: 
      - "3307:3306"
    volumes:
      - ./conf/mysql/my.cnf:/etc/mysql/my.cnf:ro
      - ./mysql/:/var/lib/mysql/:rw
      - ./log/mysql/:/var/log/mysql/:rw
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
  redis:
    container_name: myredis
    image: redis:latest
    ports:
      - "6380:6379"
